version: "3.4"

networks:
  app:
    driver: bridge

services:
  auth-service:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    container_name: "auth-service"
    ports:
      - 8080:8080
      - 8082:8082
    networks:
      - app
