// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/users/messages.proto

package users

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User - user data
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_users_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_users_messages_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_users_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_users_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_users_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_api_users_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_users_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_api_users_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_users_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SearchUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_users_messages_proto protoreflect.FileDescriptor

const file_api_users_messages_proto_rawDesc = "" +
	"\n" +
	"\x18api/users/messages.proto\x12)github.com.igortoigildin.go.contacts.user\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x04\n" +
	"\x04User\x12\x8d\x01\n" +
	"\x02id\x18\x01 \x01(\tB}\x92A\x1f2\x1dUnique identifier of the user\xe0A\x02\xbaHUrS\x10\x01\x18$2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\x02id\x12J\n" +
	"\x04name\x18\x02 \x01(\tB6\x92A\x172\x15Full name of the user\xe0A\x02\xbaH\x16r\x14\x10\x01\x18d2\x0e^[\\p{L}\\s'-]+$R\x04name\x12n\n" +
	"\x05email\x18\x03 \x01(\tBX\x92A\x1b2\x19Email address of the user\xe0A\x02\xbaH4r220^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$R\x05email\x12f\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB+\x92A%2#Timestamp when the user was created\xe0A\x03R\tcreatedAt\x12k\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB0\x92A*2(Timestamp when the user was last updated\xe0A\x03R\tupdatedAt:H\x92AE\n" +
	"C*\x04User2'User represents a contact in the system\xd2\x01\x02id\xd2\x01\x04name\xd2\x01\x05email\"\xa3\x02\n" +
	"\x11CreateUserRequest\x12J\n" +
	"\x04name\x18\x01 \x01(\tB6\x92A\x172\x15Full name of the user\xe0A\x02\xbaH\x16r\x14\x10\x01\x18d2\x0e^[\\p{L}\\s'-]+$R\x04name\x12n\n" +
	"\x05email\x18\x02 \x01(\tBX\x92A\x1b2\x19Email address of the user\xe0A\x02\xbaH4r220^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$R\x05email:R\x92AO\n" +
	"M*\x13Create User Request2'Request payload for creating a new user\xd2\x01\x04name\xd2\x01\x05email\"\xf8\x01\n" +
	"\x0eGetUserRequest\x12\x9a\x01\n" +
	"\x02id\x18\x01 \x01(\tB\x89\x01\x92A+2)Unique identifier of the user to retrieve\xe0A\x02\xbaHUrS\x10$\x18$2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\x02id:I\x92AF\n" +
	"D*\x10Get User Request2+Request payload for retrieving a user by ID\xd2\x01\x02id\"\xc2\x03\n" +
	"\x11UpdateUserRequest\x12\x98\x01\n" +
	"\x02id\x18\x01 \x01(\tB\x87\x01\x92A)2'Unique identifier of the user to update\xe0A\x02\xbaHUrS\x10$\x18$2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\x02id\x12N\n" +
	"\x04name\x18\x02 \x01(\tB:\x92A\x1b2\x19New full name of the user\xe0A\x01\xbaH\x16r\x14\x10\x01\x18d2\x0e^[\\p{L}\\s'-]+$R\x04name\x12r\n" +
	"\x05email\x18\x03 \x01(\tB\\\x92A\x1f2\x1dNew email address of the user\xe0A\x01\xbaH4r220^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$R\x05email:N\x92AK\n" +
	"I*\x13Update User Request2-Request payload for updating an existing user\xd2\x01\x02id\"\xd9\x02\n" +
	"\x12SearchUsersRequest\x12H\n" +
	"\x05query\x18\x01 \x01(\tB2\x92A%2#Search query string to filter users\xe0A\x01\xbaH\x04r\x02\x18dR\x05query\x12Y\n" +
	"\x04page\x18\x02 \x01(\x05BE\x92A82*Page number for pagination (starts from 1):\x011i\x00\x00\x00\x00\x00\x00\xf0?\xe0A\x01\xbaH\x04\x1a\x02 \x00R\x04page\x12\\\n" +
	"\tpage_size\x18\x03 \x01(\x05B?\x92A02\x18Number of items per page:\x0210Y\x00\x00\x00\x00\x00\x00Y@i\x00\x00\x00\x00\x00\x00\xf0?\xe0A\x01\xbaH\x06\x1a\x04\x18d \x00R\bpageSize:@\x92A=\n" +
	";*\x14Search Users Request2#Request payload for searching users\"\xaa\x02\n" +
	"\x13SearchUsersResponse\x12y\n" +
	"\x05users\x18\x01 \x03(\v2/.github.com.igortoigildin.go.contacts.user.UserB2\x92A,2*List of users matching the search criteria\xe0A\x03R\x05users\x12P\n" +
	"\x05total\x18\x02 \x01(\x05B:\x92A422Total number of users matching the search criteria\xe0A\x03R\x05total:F\x92AC\n" +
	"A*\x15Search Users Response2(Response payload for user search resultsB\xa4\x02\n" +
	"-com.github.com.igortoigildin.go.contacts.userB\rMessagesProtoP\x01Z\x18user/pkg/api/users;users\xa2\x02\x06GCIGCU\xaa\x02)Github.Com.Igortoigildin.Go.Contacts.User\xca\x02)Github\\Com\\Igortoigildin\\Go\\Contacts\\User\xe2\x025Github\\Com\\Igortoigildin\\Go\\Contacts\\User\\GPBMetadata\xea\x02.Github::Com::Igortoigildin::Go::Contacts::Userb\x06proto3"

var (
	file_api_users_messages_proto_rawDescOnce sync.Once
	file_api_users_messages_proto_rawDescData []byte
)

func file_api_users_messages_proto_rawDescGZIP() []byte {
	file_api_users_messages_proto_rawDescOnce.Do(func() {
		file_api_users_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_messages_proto_rawDesc), len(file_api_users_messages_proto_rawDesc)))
	})
	return file_api_users_messages_proto_rawDescData
}

var file_api_users_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_users_messages_proto_goTypes = []any{
	(*User)(nil),                  // 0: github.com.igortoigildin.go.contacts.user.User
	(*CreateUserRequest)(nil),     // 1: github.com.igortoigildin.go.contacts.user.CreateUserRequest
	(*GetUserRequest)(nil),        // 2: github.com.igortoigildin.go.contacts.user.GetUserRequest
	(*UpdateUserRequest)(nil),     // 3: github.com.igortoigildin.go.contacts.user.UpdateUserRequest
	(*SearchUsersRequest)(nil),    // 4: github.com.igortoigildin.go.contacts.user.SearchUsersRequest
	(*SearchUsersResponse)(nil),   // 5: github.com.igortoigildin.go.contacts.user.SearchUsersResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_users_messages_proto_depIdxs = []int32{
	6, // 0: github.com.igortoigildin.go.contacts.user.User.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: github.com.igortoigildin.go.contacts.user.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: github.com.igortoigildin.go.contacts.user.SearchUsersResponse.users:type_name -> github.com.igortoigildin.go.contacts.user.User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_users_messages_proto_init() }
func file_api_users_messages_proto_init() {
	if File_api_users_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_messages_proto_rawDesc), len(file_api_users_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_messages_proto_goTypes,
		DependencyIndexes: file_api_users_messages_proto_depIdxs,
		MessageInfos:      file_api_users_messages_proto_msgTypes,
	}.Build()
	File_api_users_messages_proto = out.File
	file_api_users_messages_proto_goTypes = nil
	file_api_users_messages_proto_depIdxs = nil
}
