// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/users/service.proto

package users

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_service_proto protoreflect.FileDescriptor

const file_api_users_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/users/service.proto\x12)github.com.igortoigildin.go.contacts.user\x1a\x18api/users/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x95\a\n" +
	"\vUserService\x12\xd6\x01\n" +
	"\n" +
	"CreateUser\x12<.github.com.igortoigildin.go.contacts.user.CreateUserRequest\x1a/.github.com.igortoigildin.go.contacts.user.User\"Y\x92AE\n" +
	"\x05users\x12\x0fCreate new user\x1a+Create a new user with the provided details\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x12\xd6\x01\n" +
	"\aGetUser\x129.github.com.igortoigildin.go.contacts.user.GetUserRequest\x1a/.github.com.igortoigildin.go.contacts.user.User\"_\x92AI\n" +
	"\x05users\x12\x0eGet user by ID\x1a0Retrieve user details by their unique identifier\x82\xd3\xe4\x93\x02\r\x12\v/users/{id}\x12\xd1\x01\n" +
	"\n" +
	"UpdateUser\x12<.github.com.igortoigildin.go.contacts.user.UpdateUserRequest\x1a/.github.com.igortoigildin.go.contacts.user.User\"T\x92A;\n" +
	"\x05users\x12\vUpdate user\x1a%Update an existing user's information\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/users/{id}\x12\xff\x01\n" +
	"\vSearchUsers\x12=.github.com.igortoigildin.go.contacts.user.SearchUsersRequest\x1a>.github.com.igortoigildin.go.contacts.user.SearchUsersResponse\"q\x92AY\n" +
	"\x05users\x12\fSearch users\x1aBSearch for users based on various criteria with pagination support\x82\xd3\xe4\x93\x02\x0f\x12\r/users/searchB\xd9\x02\x92A3\x12-\n" +
	"\x10User Service API\x12\x14API for user service2\x031.0*\x02\x01\x02\n" +
	"-com.github.com.igortoigildin.go.contacts.userB\fServiceProtoP\x01Z\x18user/pkg/api/users;users\xa2\x02\x06GCIGCU\xaa\x02)Github.Com.Igortoigildin.Go.Contacts.User\xca\x02)Github\\Com\\Igortoigildin\\Go\\Contacts\\User\xe2\x025Github\\Com\\Igortoigildin\\Go\\Contacts\\User\\GPBMetadata\xea\x02.Github::Com::Igortoigildin::Go::Contacts::Userb\x06proto3"

var file_api_users_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: github.com.igortoigildin.go.contacts.user.CreateUserRequest
	(*GetUserRequest)(nil),      // 1: github.com.igortoigildin.go.contacts.user.GetUserRequest
	(*UpdateUserRequest)(nil),   // 2: github.com.igortoigildin.go.contacts.user.UpdateUserRequest
	(*SearchUsersRequest)(nil),  // 3: github.com.igortoigildin.go.contacts.user.SearchUsersRequest
	(*User)(nil),                // 4: github.com.igortoigildin.go.contacts.user.User
	(*SearchUsersResponse)(nil), // 5: github.com.igortoigildin.go.contacts.user.SearchUsersResponse
}
var file_api_users_service_proto_depIdxs = []int32{
	0, // 0: github.com.igortoigildin.go.contacts.user.UserService.CreateUser:input_type -> github.com.igortoigildin.go.contacts.user.CreateUserRequest
	1, // 1: github.com.igortoigildin.go.contacts.user.UserService.GetUser:input_type -> github.com.igortoigildin.go.contacts.user.GetUserRequest
	2, // 2: github.com.igortoigildin.go.contacts.user.UserService.UpdateUser:input_type -> github.com.igortoigildin.go.contacts.user.UpdateUserRequest
	3, // 3: github.com.igortoigildin.go.contacts.user.UserService.SearchUsers:input_type -> github.com.igortoigildin.go.contacts.user.SearchUsersRequest
	4, // 4: github.com.igortoigildin.go.contacts.user.UserService.CreateUser:output_type -> github.com.igortoigildin.go.contacts.user.User
	4, // 5: github.com.igortoigildin.go.contacts.user.UserService.GetUser:output_type -> github.com.igortoigildin.go.contacts.user.User
	4, // 6: github.com.igortoigildin.go.contacts.user.UserService.UpdateUser:output_type -> github.com.igortoigildin.go.contacts.user.User
	5, // 7: github.com.igortoigildin.go.contacts.user.UserService.SearchUsers:output_type -> github.com.igortoigildin.go.contacts.user.SearchUsersResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_service_proto_init() }
func file_api_users_service_proto_init() {
	if File_api_users_service_proto != nil {
		return
	}
	file_api_users_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_service_proto_rawDesc), len(file_api_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_service_proto_goTypes,
		DependencyIndexes: file_api_users_service_proto_depIdxs,
	}.Build()
	File_api_users_service_proto = out.File
	file_api_users_service_proto_goTypes = nil
	file_api_users_service_proto_depIdxs = nil
}
