apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      version: canary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth
        version: canary
    spec:
      containers:
        - name: auth
          image: docker.io/library/auth:v2
          imagePullPolicy: "Never" # for local in minikube
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
