apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      version: green
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user
        version: green
    spec:
      containers:
      - name: user
        image: docker.io/library/user:v2
        imagePullPolicy: "Never" # for local in minikube
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
